os:
  - linux

services:
  - docker

language: node_js

node_js:
  - "8.12.0"

jdk:
  - oraclejdk8

branches:
  only:
  - master

cache:
  directories:
    - node_modules
    - $HOME/.m2
    - $HOME/.gradle

before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - export TZ=Europe/Zurich
script: ./gradlew -Pprod clean bootWar

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      cp build/libs/ln*.war src/main/docker;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build -t "guggero/ln-self-order-zeus:latest" src/main/docker/;
      docker build -t "guggero/ln-self-order-zeus:$TRAVIS_BUILD_NUMBER" src/main/docker/;
      docker push "guggero/ln-self-order-zeus:latest";
      docker push "guggero/ln-self-order-zeus:$TRAVIS_BUILD_NUMBER";
    fi
