logging:
    level:
        io.github.jhipster: DEBUG
        ch.puzzle.ln.pos: DEBUG

spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        # See section 'Use persistent development DB' in the README to set this up
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5441/zeus
        username: zeus
        password: zeus
    jpa:
        database-platform: io.github.jhipster.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    liquibase:
        contexts: dev
        drop-first: true
    mail:
        host: mail.puzzle.ch
        port: 25
        username:
        password:
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard
    thymeleaf:
        cache: false

server:
    port: 8080

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
    cache: # Cache configuration
        ehcache: # Ehcache configuration
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 100 # Number of objects in each cache entry
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
    mail: # specific JHipster mail property, for standard properties see MailProperties
        base-url: http://127.0.0.1:8080
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800

application:
    memoPrefix: 'energyKitchen '
    currencyTicker: CHF
    taxMultiplier: 0.077
    bitcoin:
        # point this to /rest/chaininfo.json if you have a full node. set it
        # to 'disabled' if you don't have a bitcoind full node running.
        restUrl: disabled
    mail:
        processorEnabled: true
    twitter:
        processorEnabled: false
        consumerKey:
        consumerSecret:
    lnd:
        host: lightning-test.puzzle.ch
        port: 10009
        certPath: classpath:/certs/dev-puzzle-test.cert
        # insert the hex values of the macaroon obtained in the previous step here!
        invoiceMacaroonHex: 0201036c6e640247030a1040609266022cad53be626c6405b088f41201301a160a0761646472657373120472656164120577726974651a170a08696e766f696365731204726561641205777269746500000620bdae00fef58499f75ee3d072c0289664d9a19ed6c1f08954dc0cd5f1e68ac908
        readonlyMacaroonHex: 0201036c6e64028a01030a1043609266022cad53be626c6405b088f41201301a0f0a07616464726573731204726561641a0c0a04696e666f1204726561641a100a08696e766f696365731204726561641a0f0a076d6573736167651204726561641a100a086f6666636861696e1204726561641a0f0a076f6e636861696e1204726561641a0d0a057065657273120472656164000006209ddc058ca81a839c9c34bf4b7f933254ed13ad17c54ad00e00e0a40f8595b807
    shop:
        allowPickupDelay: true
        openingHours:
            monday:
                open: '07:30'
                close: '19:30'
            tuesday:
                open: '07:30'
                close: '19:30'
            wednesday:
                open: '07:30'
                close: '19:30'
            thursday:
                open: '07:30'
                close: '20:30'
            friday:
                open: '07:30'
                close: '20:30'
            saturday:
                open: '07:30'
                close: '18:00'
            sunday:
                open: '10:30'
                close: '18:00'
        products:
            - title: 'Coffee'
              productKey: 'COFFEE'
              price: 4.6
              options:
                  - '"Blockaccino"'
                  - '"Latte Macchiato"'
                  - '"Espresso doppio"'
                  - '"Grosser Café Crème"'
            - title: 'Smoothie'
              productKey: 'SMOOTHIE'
              price: 4.6
              options:
                  - '"Mango Mania"'
                  - '"Himbeer Himmel"'
                  - '"Blaues Wunder"'
                  - '"Green Magic"'
            - title: 'Sandwich'
              productKey: 'SANDWICH'
              price: 6.9
              options:
                  - '"Das Bay''rische mit Fleischkäse"'
                  - '"Der Geniesser mit Lachs"'
                  - '"Der Vegetarier mit Antipasti"'
                  - '"Der Veganer mit Hummus"'
            - title: 'Pastries'
              productKey: 'PATISSERIE'
              price: 4.2
              options:
                  - '"Blechkuchen"'
                  - '"Schoggi Muffin"'
                  - '"Frucht Muffin"'
            - title: 'Müesli'
              productKey: 'MUESLI'
              price: 4.9
              options:
                  - '"Bircher Müesli"'
                  - '"Yoghurt Crunch"'
            - title: 'Salad'
              productKey: 'SALAD'
              price: 8.9
              options:
                  - '"Saison Salat"'
                  - '"Veggie Salat"'
                  - '"Salat mit Poulet"'
                  - '"Salat mit Lachs"'
        locations:
            - name: 'Pick-Up @Café-Bar, LOEB ground floor'
              key: 'COFFEE_BAR'
