management:
    endpoints:
        web:
            base-path: /
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "prometheus", "jhi-metrics", "metrics", "loggers"]
            path-mapping:
                configprops: management/configprops
                env: management/env
                health: management/health
                info: management/info
                threaddump: management/threaddump
                jhi-metrics: management/jhi-metrics
                metrics: management/metrics
                loggers: management/loggers
    endpoint:
        health:
            show-details: when_authorized
    info:
        git:
            mode: full
    health:
        mail:
            enabled: true # When using the MailService, configure an SMTP server and set this to true
    metrics:
        export:
            # Prometheus is the default metrics backend
            prometheus:
                enabled: true
                step: 60
        binders:
            jvm:
                enabled: true
            processor:
                enabled: true
            uptime:
                enabled: true
            logback:
                enabled: true
            files:
                enabled: true
            integration:
                enabled: true
        distribution:
            percentiles-histogram:
                all: true
            percentiles:
                all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
        web:
            server:
                auto-time-requests: true

logging:
    level:
        ROOT: INFO
        ch.puzzle.ln.pos: INFO
        io.github.jhipster: INFO

spring:
    application:
        name: zeus
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by gradle when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:

        mode: HTML

server:
    servlet:
        session:
            cookie:
                http-only: true

# Properties to be exposed on the /info management endpoint
info:
    # Comma separated list of profiles that will trigger the ribbon to show
    display-ribbon-on-profiles: "dev"

jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    security:
        authentication:
            jwt:
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        from: root@localhost
    swagger:
        default-include-pattern: /api/.*
        title: Zeus API
        description: Zeus API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512

application:
    memoPrefix: 'zeus '
    currencyTicker: CHF
    taxMultiplier: 0.077
    lnd:
        invoiceExpirySeconds: 300
    bitcoin:
        tickerUrl: https://blockchain.info/ticker
        tickerBackupUrl: https://public-api.lykke.com/api/AssetPairs/rate/BTCCHF
        connectTimeout: 2000
        readTimeout: 2000
    mail:
        processorEnabled: true
        subject: 'Zeus Order '
        paymentText: 'Thank you for paying with Bitcoin!'
    twitter:
        processorEnabled: false
    shop:
        allowPickupDelay: false
        products:
            - title: 'Large Beer'
              productKey: 'LARGE'
              price: 0.21
              options:
                  - '"Lightning ale"'
                  - '"Block brew"'
            - title: 'Small Beer'
              productKey: 'SMALL'
              price: 0.11
              options:
                  - '"Coin stout"'
                  - '"Thunderous amber"'
        locations:
            - name: 'Puzzle Headquarters Berne'
              key: 'PUZZLE'
